


### dev-Auth.http fremfor denne da sikkerheden på before også



### Get all user.
GET http://localhost:7070/carshop/api/users
Authorization: Bearer

### Get a single user.
GET http://localhost:7070/carshop/api/users/1

### Create a new user
POST http://localhost:7075/api/users/

{
"name": "hans",
"email": "qbnbs@akj.dk",
"password": "1234qwer",
"phone": 30117195
}

### Update a user
PUT http://localhost:7075/api/users/5

{
"name": "Lasse",
"email": "badran@youhbhbhbhbssef.dk",
"password": "1234qwer",
"phone": 30117195,
"roles": [
    "admin"
]
}


### Delete a user
DELETE http://localhost:7070/carshop/api/users/1
