### User login
POST http://localhost:7070/carshop/api/auth/login

{
"email":"badran@youssef.dk",
"password":"1234qwer"
}

### Register new user
POST http://localhost:7070/carshop/api/auth/register

{
"name": "hans",
"email": "badran@youssef.dk",
"password": "1234qwer",
"phone": 30117195
}

### Update a user
PUT http://localhost:7070/carshop/api/users/873
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYW5zQG1haWwuY29tIiwicGhvbmUiOjEyMzQ1Njc4LCJyb2xlcyI6InN0dWRlbnQsYWRtaW4iLCJpc3MiOiJUZWFtTEFIWSIsIm5hbWUiOiJIYW5zIiwiaWQiOjg3MywiZXhwIjoxNzEyNTYzMDEyLCJlbWFpbCI6ImhhbnNAbWFpbC5jb20ifQ.2k1J0Lw-9O1_Q6LgeY_WOGdqXEIri2qwQYxTX_LTdsc

{
"name": "youssef"
}