### Get all user.
GET http://localhost:7070/carshop/api/users
Authorization: Bearer

### Get a single user.
GET http://localhost:7070/carshop/api/users/1

### Create a new user
POST http://localhost:7070/carshop/api/users

{
"name": "hans",
"email": "badran@youssef.dk",
"password": "1234qwer",
"phone": 30117195
}

### Update a user
PUT http://localhost:7070/api/users/1

{
}

### Delete a user
DELETE http://localhost:7070/carshop/api/users/1
