version: '3.9'

services:
  restapi:
    image: badranyoussef/cars-api:latest
    container_name: restapi
    restart: unless-stopped
    networks:
      - frontend
      - backend
    environment:
      CONNECTION_STR: jdbc:postgresql://db:5432/
      DB_USERNAME: postgres
      DB_PASSWORD: Ys240514
      DB_NAME: car_app
      DEPLOYED: TRUE
      SECRET_KEY: 841D8A6C80CBA4FCAD32D5367C18C53B
      TOKEN_EXPIRE_TIME: 1800000
      ISSUER: cphbusiness.dk
    ports:
      - "7075:7075”

db:
  image: postgres:latest
  container_name: db
  restart: unless-stopped
  networks:
     - backend
  environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: Ys240514
  volumes:
     - ./data:/var/lib/postgresql/data/
  ports:
     - "5432:5432"


networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge